import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = ["about", "report", "todos-csr", "todos-ssr"];
  return (
    <html lang="en">
      <body className={inter.className}>
        {pages.map((page) => (
          <p key={page}>
            <Link href={`/${page}`}>{page.toUpperCase()}</Link>
          </p>
        ))}
        {children}
      </body>
    </html>
  );
}
